### ISSUE TITLE
cannot import 'validate_input_dir' error

### ISSUE THREAD

**Issue by hough129** [nipreps/nibabies#108]
Hi, I'm receiving this error when I'm trying to run nibabies, and I'm unsure why.

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nibabies", line 33, in <module>
    sys.exit(load_entry_point('nibabies', 'console_scripts', 'nibabies')())
  File "/src/nibabies/nibabies/cli/run.py", line 17, in main
    parse_args()
  File "/src/nibabies/nibabies/cli/parser.py", line 706, in parse_args
    from ..utils.bids import validate_input_dir
ImportError: cannot import name 'validate_input_dir' from 'nibabies.utils.bids' (/src/nibabies/nibabies/utils/bids.py)
```

This is how I'm trying to run it:
```
#!/bin/bash

#SBATCH -J nibabies
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --mem=20gb
#SBATCH -t 48:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=hough129@umn.edu
#SBATCH -p small,amdsmall
#SBATCH -o output_logs/nibabies_full_%A_%a.out
#SBATCH -e output_logs/nibabies_full_%A_%a.err
#SBATCH -A miran045

singularity=`which singularity`

env -i ${singularity} run --cleanenv \
-B /home/faird/shared/projects/nibabies_test/input:/data:ro \
-B /home/faird/shared/projects/nibabies_test/output:/out \
/home/faird/shared/code/external/pipelines/nibabies_0.1.0.sif /data /out participant --age-months 12
```
I built the image with the singularity pull suggested.

**Comment by mgxd** [comment]
Hi @hough129 - I'm in the process of changing the container registry used for singularity images, as releases after the initial `0.1.0` have not been pushed due to space capacity. However, you can always build from the latest docker image using the command:

```
singularity build nibabies-21.0.0rc0.sif docker://nipreps/nibabies:21.0.0rc0
```

**Comment by hough129** [comment]
@mgxd Thanks! I will try building with the docker image.

**Comment by mgxd** [comment]
closing this - if you have any problems don't hesitate to open a new issue
