### ISSUE TITLE
Final BOLD images count is off

### ISSUE THREAD

**Issue by cfilippi4** [nipreps/nibabies#134]
### What happened?

When trying to run nibabies, I got the error:

```

filippica@cn0922:/data/filippica/R21/code $ nibabies /data/filippica/R21/BIDS/OIT/ /data/filippica/R21/derivatives/OIT/nibabies participant --participant-label sub-OIT022 -w /data/filippica/R21/tmp/derivatives/OIT/nibabies --age-months 4 --nprocs 1 --omp-nthreads 1 --random-seed 0 --error-on-aroma-warnings -v --fd-spike-threshold .2 --fs-license-file /data/filippica/R21/lists/license.txt
WARNING: While bind mounting '/gs10:/gs10': destination is already in the mount point list
211008-18:17:07,915 cli INFO:
	 Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
bids-validator@1.5.7

	1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.


        Summary:                  Available Tasks:        Available Modalities: 
        727 Files, 20.17GB                                T1w                   
        54 - Subjects                                     T2w                   
        52 - Sessions                                     bold                  
                                                          fieldmap              


	If you have any questions, please post on https://neurostars.org/tags/bids.

211008-18:17:24,393 nipype.workflow IMPORTANT:
	 
    Running nibabies version 0.1.2:
      * BIDS dataset path: /data/filippica/R21/BIDS/OIT.
      * Participant list: ['OIT022'].
      * Run identifier: 20211008-181657_b979f989-bfa5-4115-b481-9dcb3ea6a949.
      * Output spaces: None.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /data/filippica/R21/derivatives/OIT/nibabies/freesurfer-infant.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/src/nibabies/nibabies/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/src/nibabies/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/src/nibabies/nibabies/workflows/base.py", line 417, in init_single_subject_wf
    subject=subject_id
  File "/src/nibabies/nibabies/utils/bids.py", line 187, in group_bolds_ref
    assert len(bolds) == sum([len(x) for x in files]), "Final BOLD images count is off"
AssertionError: Final BOLD images count is off
```

The functional fMRI data are complete.

I'm not sure what this error means and/or how to resolve. I'm running nibabies version 0.1.2.

I also checked to see if this was a part of the bids validator but got the same error when I added the --skip__bids_validation. 

Thanks for your help!

-C

### What command did you use?

nibabies /data/filippica/R21/BIDS/OIT/ /data/filippica/R21/derivatives/OIT/nibabies participant --participant-label sub-OIT022 -w /data/filippica/R21/tmp/derivatives/OIT/nibabies --age-months 4 --nprocs 1 --omp-nthreads 1 --random-seed 0 --error-on-aroma-warnings -v --fd-spike-threshold .2 --fs-license-file /data/filippica/R21/lists/license.txt

### Version

0.1.2 or older

**Comment by mgxd** [comment]
Looks like something is not going when grouping across BOLD runs. Can you run `tree /data/filippica/R21/BIDS/OIT/sub-OIT022` and post the output?

I agree that the error message is not very helpful, I will improve it.

**Comment by mgxd** [comment]
@cfilippi4 were you able to run it? 

Alternatively, if you are able to share a portion of that subject's data with me I should be able to see what's happening. I would essentially just need:

- The metadata (`.json`) files for the BOLD images
- The image dimensions (you can easily get this if you have `nibabel` installed by running
```
$ nib-ls /data/filippica/R21/BIDS/OIT/sub-OIT022/ses-20180607/func/*.gz
```

**Comment by cfilippi4** [comment]
Thanks! I was able to run that line...
python -m pip install --upgrade https://github.com/nipreps/nibabies/archive/refs/heads/master.zip

Then the error suggested that we didn't have infant freesurfer so we installed it. 

When we re-ran the original line we got the following error, indicating that it doesn't recognize the infant freesurfer version. 
```
[R21] (base) filippica@cn2879:~/2021/OIT-R21/code $ nibabies /data/filippica/R21/BIDS/OIT/ /data/filippica/R21/derivatives/OIT/nibabies participant --participant-label sub-OIT022 -w /data/filippica/R21/tmp/derivatives/OIT/nibabies --age-months 4 --nprocs 1 --omp-nthreads 1 --random-seed 0 --error-on-aroma-warnings -v --fd-spike-threshold .2 --fs-license-file /data/filippica/R21/lists/license.txt --notrack
/data/filippica/R21/code/conda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211013-13:21:59,13 cli INFO:
                Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
bids-validator does not appear to be installed
Process Process-2:
Traceback (most recent call last):
  File "/data/filippica/R21/code/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/filippica/R21/code/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nibabies/cli/workflow.py", line 20, in build_workflow
    from ..workflows.base import init_nibabies_wf
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 22, in <module>
    from ..interfaces.reports import SubjectSummary, AboutSummary
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nibabies/interfaces/reports.py", line 22, in <module>
    from smriprep.interfaces.freesurfer import ReconAll
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/smriprep/interfaces/freesurfer.py", line 28, in <module>
    from nipype.interfaces import freesurfer as fs
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nipype/interfaces/freesurfer/__init__.py", line 7, in <module>
    from .preprocess import (
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nipype/interfaces/freesurfer/preprocess.py", line 37, in <module>
    FSVersion = Info.looseversion().vstring
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nipype/interfaces/freesurfer/base.py", line 83, in looseversion
    raise RuntimeError("Unknown version string: " + ver)
RuntimeError: Unknown version string: freesurfer-linux-centos7_x86_64-infant-dev-4a14499-20210109-4a14499
```

This is the content of one of the .json files...
```
[filippica@biowulf func]$ cat sub-OIT022_ses-20180607_task-rest_run-191152_bold.json 
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"ImagingFrequency": 123.189,
	"Manufacturer": "Siemens",
	"ManufacturersModelName": "TrioTim",
	"PatientName": "OIT22",
	"PatientID": "OIT22",
	"PatientBirthDate": "2018-02-15",
	"PatientSex": "M",
	"PatientWeight": 5.98742,
	"PatientPosition": "HFS",
	"SoftwareVersions": "syngo MR B17",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "cmrr_F6_R2.0C_TR1250_V480",
	"ProtocolName": "cmrr_F6_R2.0C_TR1250_V480",
	"ScanningSequence": "EP",
	"SequenceVariant": "SK\\SS",
	"ScanOptions": "FS",
	"SequenceName": "epfid2d1_96",
	"ImageType": ["ORIGINAL", "PRIMARY", "M", "MB", "ND", "MOSAIC"],
	"SeriesNumber": 13,
	"AcquisitionTime": "19:11:52.520000",
	"AcquisitionDateTime": "2018-06-07T19:11:52.520000",
	"AcquisitionNumber": 1,
	"ImageComments": "Unaliased MB6/PE3 (remote)",
	"SliceThickness": 2,
	"SpacingBetweenSlices": 2,
	"SAR": 0.182937,
	"EchoTime": 0.0394,
	"RepetitionTime": 1.25,
	"FlipAngle": 90,
	"PartialFourier": 1,
	"BaseResolution": 96,
	"ShimSetting": [
		5196,
		-5357,
		12837,
		784,
		-22,
		1176,
		-6,
		-18	],
	"TxRefAmp": 320.284,
	"PhaseResolution": 1,
	"ReceiveCoilName": "32Ch_Head",
	"CoilString": "C:HEA;HEP",
	"PulseSequenceDetails": "%CustomerSeq%\\cmrr_mbep2d_bold",
	"MultibandAccelerationFactor": 6,
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"PhaseEncodingSteps": 96,
	"AcquisitionMatrixPE": 96,
	"ReconMatrixPE": 96,
	"BandwidthPerPixelPhaseEncode": 14.881,
	"EffectiveEchoSpacing": 0.000699998,
	"DerivedVendorReportedEchoSpacing": 0.000699998,
	"TotalReadoutTime": 0.0664998,
	"PixelBandwidth": 1796,
	"DwellTime": 2.9e-06,
	"PhaseEncodingDirection": "j-",
	"SliceTiming": [
		0,
		0.8775,
		0.5025,
		0.125,
		1.005,
		0.6275,
		0.25,
		1.13,
		0.7525,
		0.3775,
		0,
		0.8775,
		0.5025,
		0.125,
		1.005,
		0.6275,
		0.25,
		1.13,
		0.7525,
		0.3775,
		0,
		0.8775,
		0.5025,
		0.125,
		1.005,
		0.6275,
		0.25,
		1.13,
		0.7525,
		0.3775,
		0,
		0.8775,
		0.5025,
		0.125,
		1.005,
		0.6275,
		0.25,
		1.13,
		0.7525,
		0.3775,
		0,
		0.8775,
		0.5025,
		0.125,
		1.005,
		0.6275,
		0.25,
		1.13,
		0.7525,
		0.3775,
		0,
		0.8775,
		0.5025,
		0.125,
		1.005,
		0.6275,
		0.25,
		1.13,
		0.7525,
		0.3775	],
	"ImageOrientationPatientDICOM": [
		0.999949,
		-0.00240274,
		-0.00978657,
		-4.77518e-08,
		0.971158,
		-0.238438	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20210317"
}
```
We also tried to check the image dimensions with the nibabel command you sent but nib-ls is not available.

**Comment by cfilippi4** [comment]
Yes, I ran...
python -m pip install --upgrade https://github.com/nipreps/nibabies/archive/refs/heads/master.zip

The version now listed is....
filippica@cn0943:/data/filippica/R21 $ nibabies --version
NiBabies v0+unknown

I removed the build-stamp.txt (as suggested above). Now I get another error--similar to the original but more specifically about grouping BOLD runs.

Command run: 
nibabies /data/filippica/R21/BIDS/OIT/ /data/filippica/R21/derivatives/OIT/nibabies participant --participant-label sub-OIT022 -w /data/filippica/R21/tmp/derivatives/OIT/nibabies --age-months 4 --nprocs 1 --omp-nthreads 1 --random-seed 0 --error-on-aroma-warnings -v --fd-spike-threshold .2 --fs-license-file /data/filippica/R21/lists/license.txt --notrack

Error:
```
filippica@cn0943:/data/filippica/R21 $ nibabies /data/filippica/R21/BIDS/OIT/ /data/filippica/R21/derivatives/OIT/nibabies participant --participant-label sub-OIT022 -w /data/filippica/R21/tmp/derivatives/OIT/nibabies --age-months 4 --nprocs 1 --omp-nthreads 1 --random-seed 0 --error-on-aroma-warnings -v --fd-spike-threshold .2 --fs-license-file /data/filippica/R21/lists/license.txt --notrack

/data/filippica/R21/code/conda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211013-15:56:56,794 cli INFO:
	 Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
bids-validator does not appear to be installed
/data/filippica/R21/code/conda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211013-15:57:19,499 nipype.workflow IMPORTANT:
	 
    Running nibabies version 0+unknown:
      * BIDS dataset path: /data/filippica/R21/BIDS/OIT.
      * Participant list: ['OIT022'].
      * Run identifier: 20211013-155646_a2c71c63-8c4d-4f69-8dfb-a02aa546475a.
      * Output spaces: None.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /data/filippica/R21/derivatives/OIT/nibabies/sourcedata/infant-freesurfer.
/data/filippica/R21/code/conda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
211013-15:57:40,981 nipype.interface WARNING:
	 FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
Process Process-2:
Traceback (most recent call last):
  File "/data/filippica/R21/code/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/filippica/R21/code/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nibabies/cli/workflow.py", line 80, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 404, in init_single_subject_wf
    _, bold_groupings = group_bolds_ref(layout=config.execution.layout, subject=subject_id)
  File "/data/filippica/R21/code/conda/lib/python3.8/site-packages/nibabies/utils/bids.py", line 204, in group_bolds_ref
    raise RuntimeError(msg)
RuntimeError: Error encountered when grouping BOLD runs.
Combinations: [('20180607', 'j-', 0.0664998)]
Sorted files: [['/data/filippica/R21/BIDS/OIT/sub-OIT022/ses-20180607/func/sub-OIT022_ses-20180607_task-rest_run-191152_bold.nii.gz', '/data/filippica/R21/BIDS/OIT/sub-OIT022/ses-20180607/func/sub-OIT022_ses-20180607_task-rest_run-192225_bold.nii.gz']]
BOLD files: []

Please share this information with the nibabies developers at:
https://github.com/nipreps/nibabies/issues/new/choose
```

**Comment by mgxd** [comment]
Thank you, indeed it was a bug with handling some edge cases not yet encountered.

I've created a patch that should hopefully address it, would you mind testing it on your data?

```
python -m pip install --upgrade https://github.com/nipreps/nibabies/archive/refs/heads/fix/bold-grouping.zip
```

**Comment by mgxd** [comment]
I've merged it into master to help with debugging, now you can just use:

```
python -m pip install --upgrade https://github.com/nipreps/nibabies/archive/refs/heads/master.zip
```

**Comment by cfilippi4** [comment]
Yes--it stopped after about a minute and gave me a fresh line on the terminal. It occurred to me that maybe I typed something so I tried it again and let it run but again it stopped after a minute. I can try submitting it as a job but I didn't see any log files created or any of the expected output. 
```
filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies $ ls
20211012-135552_0522ca0e-a7a5-4ae2-844b-ac07be695633  20211013-163101_870d6e99-94c8-4ae6-829a-0a1e77f9bfe7
20211012-135736_14e48429-9f7b-47f5-ad9e-1c9744482809  20211013-163731_43d6a8da-5175-4d23-9773-32b8bac81088
20211013-132003_a45aff65-7206-4965-8a93-b9458385703b  20211013-174049_60a417d9-9f9f-4ab5-b26e-7b1ac3657226
20211013-132151_15b0b3bb-0700-4cba-8238-96e04f2404d4  20211013-174937_2e444989-2b89-410d-8f98-96bf531e0fe5
20211013-154941_5fb278dd-bf26-4953-b89a-82a07e514dd2  20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354
20211013-155646_a2c71c63-8c4d-4f69-8dfb-a02aa546475a
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies $ cd 20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies/20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354 $ ls
bids_db  config.toml
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies/20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354 $ cd bids_db/
[R21] (base) filippica@cn0943:/data/filippica/R21/tmp/derivatives/OIT/nibabies/20211013-175035_4141f309-4ef9-43b5-b19f-d7dd7a838354/bids_db $ ls
layout_index.sqlite
```

**Comment by mgxd** [comment]
I'm going to close this issue since the original problem seems to be fixed. I'll open a new issue with this current problem.
