### ISSUE TITLE
nibabies not starting workflows

### ISSUE THREAD

**Issue by catcamacho** [nipreps/nibabies#141]
### What happened?

I'm trying to run the latest version of nibabies using the docker container and the wrapper script.  It seems to get past the BIDS validation step but then errors out before any logs are made.  I'm not sure that I understand the traceback.  We are using the PEpolar approach for our fieldmaps and the rest of the data is pretty typical (multiband rest, multiband dwi, T1w, T2w). Thanks in advance for your help!

System Info:
2020 iMac
MacOS Big Sur version 11.6
8-Core Intel Core i7 processor
64 GB RAM

### What command did you use?

```shell
python3 nibabies_wrapper.py docker ../newborn ../derivatives participant --age-months 1
```

### Version

21.0.0

### Relevant log output

```shell
1065-AD-05001:code catcamacho$ python3 nibabies_wrapper.py docker ../newborn ../derivatives participant --age-months 1
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.8 -it -v /Users/catcamacho/Box/SEA/structure_tracing/SegmentationChecks/nibabies/bids/newborn:/data:ro -v /Users/catcamacho/Box/SEA/structure_tracing/SegmentationChecks/nibabies/bids/derivatives:/out nipreps/nibabies:21.0.0 /data /out participant --age-months 1
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
bids-validator@1.8.4

	1: [WARN] The recommended file /README is very small. Please consider expanding it with additional information about the dataset. (code: 213 - README_FILE_SMALL)

	Please visit https://neurostars.org/search?q=README_FILE_SMALL for existing conversations about this issue.

        Summary:                  Available Tasks:        Available Modalities: 
        25 Files, 266.13MB                                MRI                   
        1 - Subject                                                             
        1 - Session                                                             


	If you have any questions, please post on https://neurostars.org/tags/bids.
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
211015-16:22:11,528 nipype.workflow IMPORTANT:
	 
    Running nibabies version 21.0.0+0.gd898bf0.dirty:
      * BIDS dataset path: /data.
      * Participant list: ['1098'].
      * Run identifier: 20211015-162207_093de49d-5d4e-4166-9329-db5de54b84af.
      * Output spaces: MNIInfant:cohort-1:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /out/sourcedata/infant-freesurfer.
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/src/nibabies/nibabies/cli/workflow.py", line 80, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/src/nibabies/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/src/nibabies/nibabies/workflows/base.py", line 377, in init_single_subject_wf
    fmap_estimators = find_estimators(
  File "/usr/local/miniconda/lib/python3.8/site-packages/sdcflows/utils/wrangler.py", line 236, in find_estimators
    for fmap in layout.get(suffix=["fieldmap", "phasediff", "phase1"], **base_entities):
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 594, in get
    layouts = self._get_layouts_in_scope(scope)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 254, in _get_layouts_in_scope
    layouts = [l for l in collect_layouts(self) if l._in_scope(scope)]
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 254, in <listcomp>
    layouts = [l for l in collect_layouts(self) if l._in_scope(scope)]
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 236, in _in_scope
    pl_name = self.description.get("PipelineDescription", {}).get("Name")
AttributeError: 'NoneType' object has no attribute 'get'
nibabies: Please report errors to https://github.com/nipreps/nibabies/issues
```

**Comment by mgxd** [comment]
Thanks for the report - My guess is you may have an existing older `nibabies` directory within `../derivatives` that needs to be cleared.

**Comment by catcamacho** [comment]
Unfortunately no, I've cleared out the folder in between attempts just in case.  I deleted and remade the folder just now, reran the same command, and the output is the same (empty log folder and the same terminal output).
