### ISSUE TITLE
open file error with Docker image

### ISSUE THREAD

**Issue by catcamacho** [nipreps/nibabies#143]
### What happened?

I've run into this error during infant recon all with two different datasets (one month and six month): "error: mghRead(/opt/freesurfer/average/CNYBCH/Template3/norm.mgz, -1): could not open file"  I'm running the latest docker container using the wrapper script. Not sure why it would have issues opening files within the container? Is there something I should be doing differently?  Thanks in advance!

### What command did you use?

```shell
python3 nibabies_wrapper.py docker ../sixmonth ../derivatives/sixmonth participant --age-months 6 --fs-license-file /Applications/freesurfer/7.2.0/license.txt
```

### Version

21.0.0

### Relevant log output

```shell
Node Name: nibabies_wf.single_subject_1098_wf.infant_anat_wf.infant_surface_recon_wf.reconall
File: /out/sub-1098/log/20211017-190021_1f5229f3-8dee-4951-85c1-4a603efbeada/crash-20211017-193727-root-reconall-6a27f0c5-dd6d-4bdc-bb06-bd93b18ab8af.txt
Working Directory: /tmp/work/nibabies_wf/single_subject_1098_wf/infant_anat_wf/infant_surface_recon_wf/reconall
Inputs:
age: 6
args:
aseg_file:
environ: {}
mask_file:
newborn:
outdir:
subject_id:
subjects_dir:
t1_file:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/src/nibabies/nibabies/interfaces/freesurfer.py", line 116, in _run_interface
    return super()._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
infant_recon_all --age 6 --masked /tmp/work/nibabies_wf/single_subject_1098_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-1098_ses-sixmonth_T1w_corrected_masked.nii.gz --outdir /out/sourcedata/infant-freesurfer/sub-1098 --subject sub-1098
Standard output:
InfantReconAll scripts DIR /opt/freesurfer/bin
PWD /tmp/work/nibabies_wf/single_subject_1098_wf/infant_anat_wf/infant_surface_recon_wf/reconall

Log file is /out/sourcedata/infant-freesurfer/sub-1098/work/sub-1098_infant_recon_all.2110171937.log

Sun 17 Oct 2021 07:37:23 PM UTC
--age 6 --masked /tmp/work/nibabies_wf/single_subject_1098_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-1098_ses-sixmonth_T1w_corrected_masked.nii.gz --outdir /out/sourcedata/infant-freesurfer/sub-1098 --subject sub-1098
infant_recon_all infant-dev-4a14499
d2aa08dac073
Linux d2aa08dac073 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Processing the following subject: sub-1098
mri_convert --conform-dc /tmp/work/nibabies_wf/single_subject_1098_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-1098_ses-sixmonth_T1w_corrected_masked.nii.gz /out/sourcedata/infant-freesurfer/sub-1098/work/mprage.nu.conf.masked.nii.gz 
reading from /tmp/work/nibabies_wf/single_subject_1098_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-1098_ses-sixmonth_T1w_corrected_masked.nii.gz...
TR=10.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (0.999529, -0.026132, -0.0161073)
j_ras = (0.0227884, 0.983215, -0.181022)
k_ras = (0.0205674, 0.18057, 0.983347)
keeping DC 0 2 1
ostr RAS, width 256, size 1
K ---------------
-0.99824   0.00000   0.00000   255.00000;
 0.00000   0.00000  -1.00000   203.00000;
 0.00000   0.99824   0.00000   1.00000;
 0.00000   0.00000   0.00000   1.00000;
Kinv ---------------
-1.00177  -0.00000  -0.00000   255.45081;
-0.00000  -0.00000   1.00177  -1.00177;
-0.00000  -1.00000  -0.00000   203.00002;
-0.00000  -0.00000  -0.00000   1.00000;
Smri ---------------
 0.99776   0.02275   0.02057  -131.49341;
-0.02609   0.98148   0.18057  -136.44077;
-0.01608  -0.18070   0.98335  -58.27288;
 0.00000   0.00000   0.00000   1.00000;
Stemp ---------------
-0.99953  -0.02057   0.02279   127.53883;
 0.02613  -0.18057   0.98322  -107.43197;
 0.01611  -0.98335  -0.18102   137.42027;
 0.00000   0.00000   0.00000   1.00000;
----------------------
changing data type from float to uchar (noscale = 0)...
MRIchangeType: Building histogram 0 108941 1000, flo=0, fhi=0.999, dest_type=0
Reslicing using trilinear interpolation 
writing to /out/sourcedata/infant-freesurfer/sub-1098/work/mprage.nu.conf.masked.nii.gz...
MASKED FILE /out/sourcedata/infant-freesurfer/sub-1098/work/mprage.nu.conf.masked.nii.gz
USING the default set of training dataset....
FINDING 4 training subjects to work with...
Template3 Template2 Template4 Template10
The set of training subjects that will be used are: Template3 Template2 Template4 Template10
TEMPLATE SUBJ Template3
mri_convert /opt/freesurfer/average/CNYBCH/Template3/norm.mgz /opt/freesurfer/average/CNYBCH/Template3/norm.nii.gz 
reading from /opt/freesurfer/average/CNYBCH/Template3/norm.mgz...
error: mghRead(/opt/freesurfer/average/CNYBCH/Template3/norm.mgz, -1): could not open file
Standard error:

Return code: 1
```

**Comment by mgxd** [comment]
Thank you for the report - indeed this a problem with the container not including all possible templates (varies by age provided) needed for `infant_recon_all`.

**Comment by catcamacho** [comment]
Ah that makes sense.  Will they be added to a future version, or is there somewhere I can download them from?

**Comment by catcamacho** [comment]
Looks like it successfully got past that step with the new container.  Thanks again!
