### ISSUE TITLE
ERROR: The 'age' trait of an InfantReconAllInputSpec instance must be 0 <= an integer <= 24

### ISSUE THREAD

**Issue by hough129** [nipreps/nibabies#145]
### What happened?

Nibabies is unable to process subjects greater than the age of 24 months.

### What command did you use?

```shell
/home/faird/shared/code/external/pipelines/nibabies-21.0.0rc0.sif /data /out participant --age-months 25 \
--output-spaces MNIInfant:cohort-8 \
-w /work
```

### Version

21.0.0 release candidates (rc)

### Relevant log output

```shell
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/src/nibabies/nibabies/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/src/nibabies/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/src/nibabies/nibabies/workflows/base.py", line 288, in init_single_subject_wf
    anat_preproc_wf = init_infant_anat_wf(
  File "/src/nibabies/nibabies/workflows/anatomical/base.py", line 342, in init_infant_anat_wf
    surface_recon_wf = init_infant_surface_recon_wf(
  File "/src/nibabies/nibabies/workflows/anatomical/surfaces.py", line 47, in init_infant_surface_recon_wf
    recon = pe.Node(InfantReconAll(age=age_months), name="reconall")
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 703, in __init__
    super(CommandLine, self).__init__(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 191, in __init__
    self.inputs.trait_set(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1434, in trait_set
    setattr(self, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_types.py", line 1710, in validate
    return getattr(self, self._validate)(object, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_types.py", line 1766, in int_validate
    self.error(object, name, original_value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'age' trait of an InfantReconAllInputSpec instance must be 0 <= an integer <= 24, but a value of 25 <class 'int'> was specified.
```

**Comment by mgxd** [comment]
closing this since the cap has been removed
