### ISSUE TITLE
error from fieldmap/sdcflow 

### ISSUE THREAD

**Issue by a3sha2** [nipreps/nibabies#160]
### What happened?

this is the bug 
	1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

	Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

        Summary:                Available Tasks:        Available Modalities: 
        86 Files, 5.53GB        rest                    MRI                   
        2 - Subjects                                                          
        2 - Sessions                                                          

	If you have any questions, please post on https://neurostars.org/tags/bids.
211124-10:08:33,866 nipype.workflow IMPORTANT:
	 
    Running nibabies version 21.0.1+0.g0c07d63.dirty:
      * BIDS dataset path: /datadir.
      * Participant list: ['125632', '318409'].
      * Run identifier: 20211124-100824_80c86e89-fe88-4d0a-8a38-bf6f64921653.
      * Output spaces: MNIInfant:cohort-5:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /outdir/sourcedata/infant-freesurfer.
(base) aadebimp@ln0006 [/home/miran045/shared/projects/ABCD_XCP/HCP-D] % cat nibabies_1.sh.e8576574 
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Downloading https://templateflow.s3.amazonaws.com/tpl-UNCInfant/cohort-1/tpl-UNCInfant_cohort-1_T1w.nii.gz
100%|██████████| 3.55M/3.55M [00:00<00:00, 8.34MB/s]
Downloading https://templateflow.s3.amazonaws.com/tpl-UNCInfant/cohort-1/tpl-UNCInfant_cohort-1_label-brain_probseg.nii.gz
100%|██████████| 602k/602k [00:00<00:00, 3.63MB/s]
Downloading https://templateflow.s3.amazonaws.com/tpl-UNCInfant/cohort-1/tpl-UNCInfant_cohort-1_label-BrainCerebellumExtraction_mask.nii.gz
100%|██████████| 95.4k/95.4k [00:00<00:00, 1.41MB/s]
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/src/nibabies/nibabies/cli/workflow.py", line 80, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/src/nibabies/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/src/nibabies/nibabies/workflows/base.py", line 377, in init_single_subject_wf
    fmap_estimators = find_estimators(
  File "/usr/local/miniconda/lib/python3.8/site-packages/sdcflows/utils/wrangler.py", line 236, in find_estimators
    for fmap in layout.get(suffix=["fieldmap", "phasediff", "phase1"], **base_entities):
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 594, in get
    layouts = self._get_layouts_in_scope(scope)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 254, in _get_layouts_in_scope
    layouts = [l for l in collect_layouts(self) if l._in_scope(scope)]
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 254, in <listcomp>
    layouts = [l for l in collect_layouts(self) if l._in_scope(scope)]
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 236, in _in_scope
    pl_name = self.description.get("PipelineDescription", {}).get("Name")
AttributeError: 'NoneType' object has no attribute 'get'

### What command did you use?

```shell
env -i   singularity run -e -B /HCP-D/nibabies/rawdata/BCP_XCP_Nibabies_testing:/datadir  \
 -B /nibabies:/outdir  \
  -B /nibabies/bcpwkdir:/workdir   \
  -B /license.txt:/license.txt \
  nibabies.sif  /datadir   /outdir  participant  --age-months 14 \
   --fd-radius 35  -w /workdir --nprocs 20  --fs-license-file /license.txt --cifti-output
```

### Version

unstable

### Relevant log output

```shell
the version is 21.0.1+0.g0c07d63.dirty
```

**Comment by a3sha2** [comment]
@mgxd  thank you very much. Yes no dataset_description.json. I will add it and try again
