### ISSUE TITLE
Unable to feed Segmentation into Nibabies

### ISSUE THREAD

**Issue by hough129** [nipreps/nibabies#161]
### What happened?

Immediate failure within the first minute. I followed the documentation for `--segmentation-atlases-dir` , and I expected it to be able to run. 

### What command did you use?

```shell
env -i ${singularity} run --cleanenv \
-B /home/faird/shared/projects/nibabies_test/nibabies_seg_test:/data:ro \
-B /home/faird/shared/projects/nibabies_test/output:/out \
-B /home/faird/shared/projects/nibabies_test/license.txt:/opt/freesurfer/license.txt \
-B /home/faird/shared/projects/nibabies_test/work:/work \
/home/faird/shared/code/external/pipelines/nibabies/nibabies-21.0.1.sif /data /out participant --age-months 6 \
--output-spaces MNIInfant:cohort-3 \
--segmentation-atlases-dir /home/faird/shared/projects/nibabies_test/nibabies_seg_mask \
-w /work
```

### Version

21.0.0

### Relevant log output

```shell
You are using NiBabies-21.0.1+0.g0c07d63.dirty, and a newer version of NiBabies is available: 21.0.2.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/src/nibabies/nibabies/cli/workflow.py", line 80, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/src/nibabies/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/src/nibabies/nibabies/workflows/base.py", line 278, in init_single_subject_wf
    anat_preproc_wf = init_infant_anat_wf(
  File "/src/nibabies/nibabies/workflows/anatomical/base.py", line 216, in init_infant_anat_wf
    anat_seg_wf = init_anat_seg_wf(
  File "/src/nibabies/nibabies/workflows/anatomical/segmentation.py", line 101, in init_anat_seg_wf
    tmpl_anats, tmpl_segs = _parse_segmentation_atlases(anat_modality, template_dir)
  File "/src/nibabies/nibabies/workflows/anatomical/segmentation.py", line 191, in _parse_segmentation_atlases
    assert anats
AssertionError
```

### Add any additional information or context about the problem here.

The version I'm using is not listed - I'm using 20.0.1, and I'm currently pulling 20.0.2 to see if the issue persists.

My files within the segmentation atlases dir are called:
`sub-CENSORED_ses-6mo_acq-mask_T1w.nii.gz`
`sub-CENSORED_ses-6mo_acq-Segmentation.nii.gz`

**Comment by mgxd** [comment]
Can you run `tree` on the directory and paste the outputs?

For reference, this is a sample directory:

```
jlf-templates/
├── Template01
│   ├── Segmentation.nii.gz
│   ├── T1w_brain.nii.gz
│   └── T2w_brain.nii.gz
└── Template02
    ├── Segmentation.nii.gz
    ├── T1w_brain.nii.gz
    └── T2w_brain.nii.gz
```

**Comment by hough129** [comment]
Oh! My tree definitely does not look like that. I need another subfolder. Thanks Mathias. Is this tree documented somewhere?

**Comment by mgxd** [comment]
Nope, just described in https://nibabies.readthedocs.io/en/latest/usage.html#more-information-on-command-line-arguments

I'll add a `FAQs` section to the documentation outlining it in more detail. If you ever see the documentation lacking, feel free to open an issue (or a pull request with the improved changes)

**Comment by hough129** [comment]
It failed again, and it doesn't look like tree is available on MSI.

Here is my fake tree:

```
jlf-templates/
├── Template01
│   ├── sub-CENSORED_ses-6mo_acq-mask_T1w.nii.gz
│   ├──sub-CENSORED_ses-6mo_acq-Segmentation.nii.gz
```

**Comment by mgxd** [comment]
oh, this is a problem with your bindings.

`--segmentation-atlases-dir /home/faird/shared/projects/nibabies_test/nibabies_seg_mask` is a local path, not a path within the container.

**Comment by mgxd** [comment]
I would recommend using the [`nibabies-wrapper`](https://nibabies.readthedocs.io/en/latest/installation.html#installing-the-nibabies-wrapper), which should make the whole binding process easier

**Comment by hough129** [comment]
Oh, you are right - I added it via -B, and it is working now. Thanks for your help, Mathias!
