### ISSUE TITLE
Feeding an External Segmentation in

### ISSUE THREAD

**Issue by hough129** [nipreps/nibabies#163]
### What happened?

I tried feeding an external segmentation in. It fails ~1:30 minutes in with this error. It seems like it might be a file formatting issue. Because I am feeding segmentations that are not produced by JLF, can you clarify the specs needed for a segmentation and mask to be fed in? Thanks.

### What command did you use?

```shell
env -i ${singularity} run --cleanenv \
-B /home/faird/shared/projects/nibabies_test/nibabies_seg_test:/data:ro \
-B /home/faird/shared/projects/nibabies_test/output:/out \
-B /home/faird/shared/projects/nibabies_test/license.txt:/opt/freesurfer/license.txt \
-B /home/faird/shared/projects/nibabies_test/work:/work \
-B /home/faird/shared/projects/nibabies_test/jlf-templates:/templates \
/home/faird/shared/code/external/pipelines/nibabies/nibabies-21.0.2.sif /data /out participant --age-months 6 \
--output-spaces MNIInfant:cohort-3 \
--segmentation-atlases-dir /templates \
-w /work
```

### Version

21.0.0

### Relevant log output

```shell
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nipype/algorithms/confounds.py:1181: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
/usr/local/miniconda/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nipype/algorithms/confounds.py:1181: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.8/site-packages/nipype/algorithms/confounds.py:1181: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.8/site-packages/nipype/algorithms/confounds.py:1181: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/resampling.py:531: UserWarning: Casting data from int32 to float32
  warnings.warn("Casting data from %s to %s" % (data.dtype.name, aux))
/usr/local/miniconda/lib/python3.8/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "
/usr/local/miniconda/lib/python3.8/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nibabies", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/cli/run.py", line 91, in main
    nibabies_wf.run(**config.nipype.get_plugin())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node jointfusion.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_label_fusion' trait of a JointFusionOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/anat_seg_wf/jointfusion/fusion_labels.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/anat_seg_wf/jointfusion/fusion_labels.nii.gz' for output 'out_label_fusion' of a JointFusion interface
```

### Add any additional information or context about the problem here.

Used 20.0.2 - not an option on the versions.

**Comment by mgxd** [comment]
Was a crashfile produced in the output directory? `<output-dir>/<subject>/log/UUID/crash-*.txt`

The only expectations the segmentations require:
- The labels correspond to the FreeSurfer lookup table (LUT)
- The anatomicals are masked.

**Comment by hough129** [comment]
Here is the crash file. The expectations you listed for the segmentations should be met.

```
Node: nibabies_wf.single_subject_CENSORED_wf.infant_anat_wf.anat_seg_wf.jointfusion
Working directory: /work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/anat_seg_wf/jointfusion

Node inputs:

alpha = 0.1
args = <undefined>
atlas_image = [['/work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/anat_seg_wf/apply_atlas/mapflow/_apply_atlas0/sub-CENSORED_ses-6mo_acq-mask_T1w_trans.nii.gz']]
atlas_segmentation_image = ['/work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/anat_seg_wf/apply_seg/mapflow/_apply_seg0/sub-CENSORED_ses-6mo_acq-Segmentation_trans.nii.gz']
beta = 2.0
constrain_nonnegative = False
dimension = 3
environ = {'NSLOTS': '8'}
exclusion_image = <undefined>
exclusion_image_label = <undefined>
mask_image = <undefined>
num_threads = 8
out_atlas_voting_weight_name_format = <undefined>
out_intensity_fusion_name_format = <undefined>
out_label_fusion = fusion_labels.nii.gz
out_label_post_prob_name_format = <undefined>
patch_metric = <undefined>
patch_radius = <undefined>
retain_atlas_voting_images = False
retain_label_posterior_images = False
search_radius = [3, 3, 3]
target_image = [['/work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/coregistration_wf/apply_mask/sub-CENSORED_ses-6mo_run-001_T1w_corrected_masked.nii.gz']]
verbose = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node jointfusion.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_label_fusion' trait of a JointFusionOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/anat_seg_wf/jointfusion/fusion_labels.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/work/nibabies_wf/single_subject_CENSORED_wf/infant_anat_wf/anat_seg_wf/jointfusion/fusion_labels.nii.gz' for output 'out_label_fusion' of a JointFusion interface
```

**Comment by mgxd** [comment]
does your `--segmentation-atlases-dir` only contain 1 template?

**Comment by hough129** [comment]
Yes.

**Comment by mgxd** [comment]
You will need to have 2 or more segmentations - I'll add that to the documentation.

**Comment by ericfeczko** [comment]
@mgxd I'm curious, why are 2 or more segmentations needed if we're providing an external segmentation?

**Comment by mgxd** [comment]
Does JLF work with a single template? To my knowledge, it makes the assumption there are multiple atlases since it is using a voting scheme.

**Comment by ericfeczko** [comment]
I think you may be talking past one another. The segementation @hough129 is trying to add isn't a template itself.  @hough129 Is trying to put an infant through nibabies where we already have the infant's freesurfer segmentation already and wouldn't need JLF.

**Comment by mgxd** [comment]
Oh, that's not implemented yet.

**Comment by ericfeczko** [comment]
Should we add a separate issue for this as a feature request?

**Comment by mgxd** [comment]
sure
