### ISSUE TITLE
Unstable Derivatives Version Failure

### ISSUE THREAD

**Issue by hough129** [nipreps/nibabies#177]
### What happened?

I'm struggling to figure out all of the requirements for feeding in the external segmentations.

### What command did you use?

```shell
env -i ${singularity} run --cleanenv \
-B /home/faird/shared/projects/nibabies_test/nibabies_seg_test:/data:ro \
-B /home/faird/shared/projects/nibabies_test/output:/out \
-B /home/faird/shared/projects/nibabies_test/license.txt:/opt/freesurfer/license.txt \
-B /home/faird/shared/projects/nibabies_test/work:/work \
-B /home/faird/shared/projects/nibabies_test/derivatives:/derivatives \
/home/faird/shared/code/external/pipelines/nibabies/nibabies-21.0.2_derivatives.sif /data /out participant --age-months 6 \
--output-spaces MNIInfant:cohort-3 \
--cifti-output 91k \
--derivatives /derivatives \
-w /work
```

### What version of NiBabies are you using?

21.0.2 unstable

### Relevant log output

```shell
(node:1299919) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/cli/workflow.py", line 80, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 263, in init_single_subject_wf
    anat_preproc_wf = init_infant_anat_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/anatomical/base.py", line 295, in init_infant_anat_wf
    wf.connect([
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 183, in connect
    raise Exception(
Exception: Trying to connect infant_anat_wf.coregistration_wf:outputnode.t1w_mask to infant_anat_wf.anat_derivatives_wf:inputnode.t1w_mask but input 'inputnode.t1w_mask' of node 'infant_anat_wf.anat_derivatives_wf' is already
connected.
```

**Comment by mgxd** [comment]
can you post the `tree` of `/home/faird/shared/projects/nibabies_test/derivatives`?

**Comment by hough129** [comment]
derivatives
└── precomputed
    ├── dataset_description.json
    └── sub-censored
        └── anat
            ├── sub-censored_ses-6mo_space-orig_desc-aseg_dseg.nii.gz
            └── sub-censored_ses-6mo_space-orig_desc-aseg_mask.nii.gz

**Comment by mgxd** [comment]
you need to point to `/home/faird/shared/projects/nibabies_test/derivatives/precomputed`

**Comment by hough129** [comment]
I also tried that, but I might not have had the dataset_description.json in there at that point - I will try again now.

**Comment by mgxd** [comment]
also you may need a `ses-6mo` after the `sub-censored` directory

```
derivatives
└── precomputed
    ├── dataset_description.json
    └── sub-censored
        └── ses-6mo
            └── anat
               ├── sub-censored_ses-6mo_space-orig_desc-aseg_dseg.nii.gz
               └── sub-censored_ses-6mo_space-orig_desc-aseg_mask.nii.gz

```

**Comment by hough129** [comment]
This error:
```
(node:3178875) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/cli/workflow.py", line 80, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 263, in init_single_subject_wf
    anat_preproc_wf = init_infant_anat_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/anatomical/base.py", line 295, in init_infant_anat_wf
    wf.connect([
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 183, in connect
    raise Exception(
Exception: Trying to connect infant_anat_wf.coregistration_wf:outputnode.t1w_mask to infant_anat_wf.anat_derivatives_wf:inputnode.t1w_mask but input 'inputnode.t1w_mask' of node 'infant_anat_wf.anat_derivatives_wf' is already
connected.
```
With this command:
```
env -i ${singularity} run --cleanenv \
-B /home/faird/shared/projects/nibabies_test/nibabies_seg_test:/data:ro \
-B /home/faird/shared/projects/nibabies_test/output:/out \
-B /home/faird/shared/projects/nibabies_test/license.txt:/opt/freesurfer/license.txt \
-B /home/faird/shared/projects/nibabies_test/work:/work \
-B /home/faird/shared/projects/nibabies_test/derivatives/precomputed:/derivatives \
/home/faird/shared/code/external/pipelines/nibabies/nibabies-21.0.2_derivatives.sif /data /out participant --age-months 6 \
--output-spaces MNIInfant:cohort-3 \
--cifti-output 91k \
--derivatives /derivatives \
-w /work 
```
With this tree:
```
derivatives
└── precomputed
    ├── dataset_description.json
    └── sub-censored
        └── ses-6mo
            └── anat
                ├── sub-censored_ses-6mo_space-orig_desc-aseg_dseg.nii.gz
                └── sub-censored_ses-6mo_space-orig_desc-aseg_mask.nii.gz
```

**Comment by mgxd** [comment]
oh, your mask is not named correctly... it should be

`sub-censored_ses-6mo_space-orig_desc-brain_mask.nii.gz`

**Comment by mgxd** [comment]
but regardless, this needs a quick fix.

**Comment by hough129** [comment]
```
(node:3859611) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/cli/workflow.py", line 80, in build_workflow
    retval["workflow"] = init_nibabies_wf()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 68, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/base.py", line 263, in init_single_subject_wf
    anat_preproc_wf = init_infant_anat_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/workflows/anatomical/base.py", line 295, in init_infant_anat_wf
    wf.connect([
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 183, in connect
    raise Exception(
Exception: Trying to connect infant_anat_wf.coregistration_wf:outputnode.t1w_mask to infant_anat_wf.anat_derivatives_wf:inputnode.t1w_mask but input 'inputnode.t1w_mask' of node 'infant_anat_wf.anat_derivatives_wf' is already
connected.
```

I'm still getting the same thing with the modifications to the naming:
```
derivatives
└── precomputed
    ├── dataset_description.json
    └── sub-censored
        └── ses-6mo
            └── anat
                ├── sub-censored_ses-6mo_space-orig_desc-aseg_dseg.nii.gz
                └── sub-censored_ses-6mo_space-orig_desc-brain_mask.nii.gz
```

**Comment by mgxd** [comment]
Ok, there seem to be two errors here, which is making this confusing. 


```
Exception: Trying to connect infant_anat_wf.coregistration_wf:outputnode.t1w_mask to infant_anat_wf.anat_derivatives_wf:inputnode.t1w_mask but input 'inputnode.t1w_mask' of node 'infant_anat_wf.anat_derivatives_wf' is already
connected.
```

This is happening because the precomputed mask is not being found. Looking at the log in https://github.com/nipreps/nibabies/issues/177#issuecomment-1012382176, we can see 

```
/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py:127: UserWarning: Derivative indexing was requested, but no valid datasets were found in the specified locations (['/derivatives']). Note that all BIDS-Derivatives datasets must meet all the requirements for BIDS-Raw datasets (a common problem is to fail to include a 'dataset_description.json' file in derivatives datasets).
Example contents of 'dataset_description.json':
{"Name": "Example dataset", "BIDSVersion": "1.0.2", "GeneratedBy": [{"Name": "Example pipeline"}]}
```

Does your `dataset_description.json` include all the required fields?


---

I just submitted a patch (https://github.com/nipreps/nibabies/commit/7905595fd74a27b500540f2be3094a6f9d4f35f2) since there also was a bug that assumed derivatives had no session id.

**Comment by hough129** [comment]
I'm going to refine my dataset_description.json - I'm not used to its contents of the file actually being important. I will post it here before I try the patch.

**Comment by effigies** [comment]
For derivative datasets, it should also have `"DatasetType": "derivative"`, though I'm not sure that anything validates that at this point.

**Comment by hough129** [comment]
Building the new image now.

This is the contents of the `dataset_description.json` I plan on using for reference:
```
{
    "Name": "BIBSnet",
    "BIDSVersion": "1.4.0",
    "DatasetType": "derivative",
    "GeneratedBy": [
        {
            "Name": "BIBSnet",
            "Version": "0+unknown",
            "CodeURL": "https://github.com/DCAN-Labs/BIBSnet"
        }
    ],
    "HowToAcknowledge": "TODO"
}
```

**Comment by hough129** [comment]
It's been running without fail for 13 minutes now - I will let you know if it makes it successfully through the run on Monday.
