### ISSUE TITLE
UNCInfant Atlas output space error

### ISSUE THREAD

**Issue by ajdneuro12** [nipreps/nibabies#187]
### What happened?

Hello,
Thanks for this great tool, so exciting!

I am getting an error trying to use the UNCInfant as output space, see below:

 use of ``template_resolution`` is deprecated
220207-19:32:10,865 nipype.workflow INFO:
	 [Node] Finished "registration", elapsed time 1.461977s.
220207-19:32:10,865 nipype.workflow WARNING:
	 Storing result file without outputs
220207-19:32:10,866 nipype.workflow WARNING:
	 [Node] Error on "nibabies_wf.single_subject_001_wf.infant_anat_wf.anat_norm_wf.registration" (/gpfs/ysm/project/scheinost/ajd224/bcpraw/work/nibabies_wf/single_subject_001_wf/infant_anat_wf/anat_norm_wf/_template_UNCInfantcohort-1/registration)
220207-19:32:11,264 nipype.workflow ERROR:
	 Node registration.a0 failed to run on host c20n09.farnam.hpc.yale.internal.
220207-19:32:11,264 nipype.workflow ERROR:
	 Saving crash info to /out/sub-001/log/20220207-191113_909421ef-3193-4893-9ace-9188c687bed5/crash-20220207-193211-ajd224-registration.a0-43d35777-92de-4895-bfdc-9d62ce44eebb.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node registration.

Best,
Alex

### What command did you use?

```shell
nibabies-wrapper singularity bids/ nibabies_output/ participant --fs-license-file nibabies_setupfiles/fslicense.txt --image ../singularity_images/nibabies-21.0.2.sif --age-months 3 --skip-bids-validation --output-spaces UNCInfant:cohort-1 --fs-no-reconall
```

### What version of NiBabies are you using?

nibabies-21.0.2.sif

**Comment by mgxd** [comment]
What are the contents of the crashfile? 
```
nibabies_output/sub-001/log/20220207-191113_909421ef-3193-4893-9ace-9188c687bed5/crash-20220207-193211-ajd224-registration.a0-43d35777-92de-4895-bfdc-9d62ce44eebb.txt
```

**Comment by ajdneuro12** [comment]
Hi, sorry for the delay, retried with the 22.0.0, here is the crash file contents:

Node: nibabies_22_0_wf.single_subject_NDARINVAZ021WML_wf.infant_anat_wf.anat_norm_wf.registration
Working directory: /gpfs/ysm/project/scheinost/ajd224/bcpraw/work/nibabies_22_0_wf/single_subject_NDARINVAZ021WML_wf/infant_anat_wf/anat_norm_wf/_template_UNCInfantcohort-1/registration

Node inputs:

explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
reference = T1w
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = <undefined>
template_spec = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '[]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/norm.py", line 183, in _run_interface
    ants_args = self._get_ants_args()
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/norm.py", line 457, in _get_ants_args
    args["fixed_image"] = mask(
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/norm.py", line 504, in mask
    mask_nii = nb.load(mask_file)
  File "/opt/conda/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '[]'



My command was: nibabies-wrapper singularity bids/ nibabies_output/ participant --fs-license-file nibabies_setupfiles/fslicense.txt --image ../singularity_images/nibabies-22.0.0.sif --age-months 2 --skip-bids-validation --output-spaces UNCInfant:cohort-1 --fs-no-reconall


Thank you!

**Comment by mgxd** [comment]
@ajdneuro12 that is strange - I'm not sure why you are getting the `MNI152NLin2009cAsym` as the target template...

Maybe we can check a few things:
- What is the generated command produced by the nibabies-wrapper? This looks like `RUNNING: ...`
- Can you remove `--skip-bids-validation`?

**Comment by mgxd** [comment]
ah, I was able to reproduce this:

```
Node: nibabies_22_0_wf.single_subject_01_wf.infant_anat_wf.anat_norm_wf.registration
Working directory: /scratch/nibabies_22_0_wf/single_subject_01_wf/infant_anat_wf/anat_norm_wf/_template_UNCInfantcohort-1/registration

Node inputs:

explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = /scratch/nibabies_22_0_wf/single_subject_01_wf/infant_anat_wf/anat_norm_wf/_template_UNCInfantcohort-1/trunc_mov/sub-01_ses-1mo_run-001_T1w_corrected_maths.nii.gz
moving_mask = /scratch/nibabies_22_0_wf/single_subject_01_wf/infant_anat_wf/coregistration_wf/thr_mask/tpl-UNCInfant_cohort-1_label-brain_probseg_trans_trans_mask.nii.gz
num_threads = 2
orientation = RAS
reference = T1w
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = UNCInfant
template_resolution = None
template_spec = {'cohort': '1'}

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '[]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/norm.py", line 183, in _run_interface
    ants_args = self._get_ants_args()
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/norm.py", line 457, in _get_ants_args
    args["fixed_image"] = mask(
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/norm.py", line 504, in mask
    mask_nii = nb.load(mask_file)
  File "/opt/conda/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '[]'
```

So this is definitely a problem with nibabies

**Comment by mgxd** [comment]
@ajdneuro12 can you give the new release (`21.0.1`) a try and see if it fixes your problem?
