### ISSUE TITLE
Unable to run new singularity image

### ISSUE THREAD

**Issue by hough129** [nipreps/nibabies#188]
### What happened?

22.0.0rc0 immediately fails

### What command did you use?

```shell
env -i ${singularity} run --cleanenv \
-B /home/faird/shared/projects/Julia_test/nibabies_test/sub-12mo-1run:/data:ro \
-B /home/faird/shared/projects/Julia_test/nibabies_test/test_output_cifti:/out \
-B /home/faird/shared/projects/nibabies_test/license.txt:/opt/freesurfer/license.txt \
-B /home/faird/shared/projects/Julia_test/nibabies_test/work/:/work \
/home/faird/shared/code/external/pipelines/nibabies/nibabies-22.0.0rc0.sif /data /out participant --age-months 12 \
--output-spaces MNIInfant:cohort-5 \
--cifti-output 91k \
-w /work
```

### What version of NiBabies are you using?

22.0.0rc0

### Relevant log output

```shell
(node:3058679) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nibabies", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/cli/run.py", line 31, in main
    [config.to](http://config.to/)_filename(config_file)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/config.py", line 684, in to_filename
    filename.write_text(dumps())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabies/config.py", line 676, in dumps
    from toml import dumps
ModuleNotFoundError: No module named 'toml'
```

### Add any additional information or context about the problem here.

I tried pulling the image twice - the failure happened the same way both times.

**Comment by hough129** [comment]
This has been resolved by the updated image. Thanks all.
