### ISSUE TITLE
NodeExecutionError when running nibabies on subject without external segmentation

### ISSUE THREAD

**Issue by lundq163** [nipreps/nibabies#227]
### What happened?

I am getting Node Execution error when trying to run version 22.1.0rc1 on a subject without an external segmentation

### What command did you use?

```shell
#!/bin/bash -l

#SBATCH -J nibabies
#SBATCH -c 8
#SBATCH --mem=320G
#SBATCH -t 48:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lundq163@umn.edu
#SBATCH -p msismall
#SBATCH -o output_logs/nibabies_full_%A_%a.out
#SBATCH -e output_logs/nibabies_full_%A_%a.err
#SBATCH -A miran045

singularity=`which singularity`

env -i ${singularity} run --cleanenv \
-B /home/feczk001/shared/projects/XCPD_Nibabies_fixes/input/:/data:ro \
-B /home/feczk001/shared/projects/XCPD_Nibabies_fixes/derivatives/nibabies/:/out \
-B /home/feczk001/shared/projects/Jacob_test/nibabies_xcpd_sbatches/license.txt:/opt/freesurfer/license.txt \
-B /home/feczk001/shared/projects/XCPD_Nibabies_fixes/work/:/work \
-B /home/faird/shared/code/external/pipelines/smriprep/smriprep:/opt/conda/lib/python3.9/site-packages/smriprep/ \
/home/faird/shared/code/external/pipelines/nibabies/nibabies_22.1.0rc1.sif /data /out participant --participant-label ###### --age-months # \
--cifti-output 91k \
--topup-max-vols 2 \
--nprocs 8 \
--omp-nthreads 8 \
-w /work
```

### What version of NiBabies are you using?

22.1.0rc1

### Relevant log output

```shell
You are using NiBabies-21.1.0rc1, and a newer version of NiBabies is available: 22.0.2.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
Traceback (most recent call last):
  File "/opt/conda/bin/nibabies", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/nibabies/cli/run.py", line 91, in main
    nibabies_wf.run(**_plugin)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node reconall.

RuntimeError: subprocess exited with code 1.
```

**Comment by mgxd** [comment]
@lundq163 it looks like something is going wrong when running `infant_recon_all` - if you go into your freesurfer outputs directory, there should be a `work/` directory that contains a log file. Can you share that?

**Comment by lundq163** [comment]
@mgxd we dont have the `work/` directory any more but I can reprocess a subject to send that to you for debugging

**Comment by lundq163** [comment]
[sub-557806_infant_recon_all.2208042204.log](https://github.com/nipreps/nibabies/files/9271009/sub-557806_infant_recon_all.2208042204.log)
[summary.sub-557806_infant_recon_all.2208042204 (1).log](https://github.com/nipreps/nibabies/files/9271012/summary.sub-557806_infant_recon_all.2208042204.1.log)

here are the two log files from that path

**Comment by mgxd** [comment]
Thanks - it looks like we might be missing a shared object that numpy is relying on:

```
ImportError: libopenblasp-r0-382c8f3a.3.5.dev.so: cannot open shared object file: No such file or directory
```

**Comment by madisoth** [comment]
As a small update @lundq163 and I found a temporary workaround by binding a copy of `/opt/freesurfer/python/lib/python3.6/site-packages/numpy/.libs` from the 21.0.2 container to the same location in 22.1.0.
