### ISSUE TITLE
23.1.0 release candidate 1 version throw errors about can not find precomputed segmentation while using --surface-recon-method mcribs

### ISSUE THREAD

**Issue by yanbin-niu** [nipreps/nibabies#321]
### What happened?

Hi,

Today, we experimented with the latest version of nibabies (23.1.0rc1) to appreciate its performance in single anatomical processing. Unfortunately, we encountered an issue where the mcribs run was unable to locate the precomputed segmentation. Previously, when we used version 23.1.0rc0 with the `--surface-recon-method mcribs` flag and the `--derivatives /opt/derivatives/precomputed`, we do not have problems. Could you please assist us in resolving this issue with the new version?

Best regards,
Yanbin

### What command did you use?

```shell
docker run --rm -e DOCKER_VERSION_8395080871=23.1.0rc1 -it ' \
                 '-v /Applications/freesurfer/7.1.1/license.txt:/opt/freesurfer/license.txt:ro ' \
                 '-v /Volumes/SEALab_Projects/BABIES/MRI/newborn/bids:/data:ro ' \
                 '-v /Volumes/SEALab_Projects/BABIES/MRI/newborn/derivatives/Nibabies:/out ' \
                 '-v /Volumes/SEALab_Projects/BABIES/MRI/newborn/derivatives/precomputed:/opt/derivatives/precomputed ' \
                 '-v /Volumes/SEALab_Projects/BABIES/MRI/newborn/derivatives/work/nibabies_work:/scratch ' \
                 'nipreps/nibabies:23.1.0rc1 /data /out participant ' \
                 f'--skip_bids_validation --age-months 1 --nprocs 6 --participant-label {subject_id} ' \
                 '--derivatives /opt/derivatives/precomputed -w /scratch --surface-recon-method mcribs --anat-only
```

### What version of NiBabies are you using?

nibabies:23.1.0rc1

### Relevant log output

```shell
231112-91:09:7,756 nipype.workflow IMPORTANT:
Running nibabies version 23.1.0rc1:
* BIDS dataset path: /data.
Participant list: [['1123'，newborn']].*
*Run identifier: 20231112-010306 f834c77f-d7ea-43c8-89a2-87ec0a6ca8b3.
* Output spaces: MNIInfant.* Pre-run FreeSurfer's SUBJECTS DIR: /out/sourcedata/freesurfer.231112-91:09:7,872 cli WARNING:
-age-months' is deprecated and will be removed in a future release.please use a 'sessions.tsy' orparticipants,tsy' file to track participants age.Traceback (most recent call last):File "/opt/conda/envs/nibabies/bin/nibabies", line 8,in <module>
svs.exit(main())
File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/run,py", line 63，in mainretval = build workflow(confia file)
File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/workflow.py", line 80, in build workflow
retvall"workflow"1 = init nibabies wf(config,execution,unigue labels)File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/workflows/base.py", line 130, in initnibabies wf
```

**Comment by mgxd** [comment]
We have reworked `--derivatives` in https://github.com/nipreps/nibabies/pull/305 - you will likely have to update your derivatives space, and add the `SpatialRefernce` metadata.

Thank you for testing out the prerelease - looks like we will need to update the documentation prior to the actual release 😄
