### ISSUE TITLE
"'resource_filename' is not defined" error on multi-echo dataset

### ISSUE THREAD

**Issue by tsalo** [nipreps/nibabies#343]
### What happened?

Running Nibabies on a multi-echo infant dataset led to the error `name 'resource_filename' is not defined`.

### What command did you use?

```shell
singularity run --home $HOME --cleanenv \
    -B /cbica/home/salot/datasets/infant_dset:/data \
    /cbica/home/salot/singularity/nibabies-24_0_0dev.simg \
    /data \
    /data/derivatives/nibabies \
    participant \
    -w /cbica/home/salot/datasets/infant_dset_work \
    --nprocs 1 \
    --omp-nthreads 1 \
    --output-spaces func T1w MNIInfant:cohort-1 \
    --me-output-echos \
    --project-goodvoxels \
    --cifti-output \
    --fs-license-file freesurfer_license.txt \
    --skip_bids_validation
```

### What version of NiBabies are you using?

v24.1.0.dev17+ge29ee42 (unstable from 2024/02/07)

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/bin/nibabies", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/run.py", line 59, in main
    retval = build_workflow(config_file)
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/workflow.py", line 76, in build_workflow
    retval["workflow"] = init_nibabies_wf(config.execution.unique_labels)
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/workflows/base.py", line 130, in init_nibabies_wf
    single_subject_wf = init_single_subject_wf(
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/workflows/base.py", line 459, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file, spaces, has_fieldmap=has_fieldmap)
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/workflows/bold/base.py", line 964, in init_func_preproc_wf
    subcortical_mni_alignment_wf = init_subcortical_mni_alignment_wf()
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/workflows/bold/alignment.py", line 144, in init_subcortical_mni_alignment_wf
    atlas_xfm = resource_filename("nibabies", "data/MNIInfant_to_MNI1526NLinAsym.mat")
NameError: name 'resource_filename' is not defined
```

### Add any additional information or context about the problem here.

It's a multi-echo infant dataset that @madisoth shared with me.

**Comment by madisoth** [comment]
Just checked and can confirm this issue happens for single-echo BOLD data too, and that it doesn't happen in 24.0.0a1.
