### ISSUE TITLE
mri_coreg crash

### ISSUE THREAD

**Issue by scott-huberty** [nipreps/nibabies#363]
### What happened?

I initially raised this in #359 , and at the time thought the error was specific to my system, but I'm now getting the same error across multiple subjects, computers, Nibabies versions, etc., so would like to officially open up a bug report. Here is the error in one line:

`FileNotFoundError: [Errno 2] No such file or directory: '/scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta'`

### What command did you use?

```shell
docker run -e DOCKER_VERSION_8395080871=23.1.0 -it \
    -v /Path/to/license.txt:/opt/freesurfer/license.txt:ro \
    -v /Path/to/bids:/data:ro \
    -v /Path/to/derivatives/Nibabies:/out \
    -v /Path/to/derivatives/precomputed:/opt/derivatives/precomputed \
    -v /Path/to/nibabies/nibabies:/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies:ro \
    -v /Path/to/derivatives/work/nibabies_work:/scratch \
    nipreps/nibabies:unstable /data /out participant \
    --age-months 1 \
    --participant-label 999 \
    --derivatives /opt/derivatives/precomputed \
    -w /scratch \
    --surface-recon-method mcribs \
    --cifti-output 91k \
    --verbose
```

### What version of NiBabies are you using?

Dev

### Relevant log output

```shell
Node: nibabies_24_1_wf.single_subject_1390_newborn_wf.func_preproc_ses_newborn_task_restPA_run_01_wf.bold_reg_wf.bbreg_wf.mri_coreg
Working directory: /scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/bold_reg_wf/bbreg_wf/mri_coreg

Node inputs:

args = <undefined>
brute_force_limit = <undefined>
brute_force_samples = <undefined>
compress_report = auto
conform_reference = <undefined>
dof = 6
environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects'}
ftol = 0.0001
initial_rotation = <undefined>
initial_scale = <undefined>
initial_shear = <undefined>
initial_translation = <undefined>
linmintol = 0.01
max_iters = <undefined>
no_brute_force = <undefined>
no_coord_dithering = <undefined>
no_cras0 = <undefined>
no_intensity_dithering = <undefined>
no_smooth = <undefined>
num_threads = 1
out_lta_file = True
out_params_file = <undefined>
out_reg_file = <undefined>
out_report = report.svg
ref_fwhm = <undefined>
reference_file = <undefined>
reference_mask = <undefined>
saturation_threshold = <undefined>
sep = [4]
source_file = /scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/final_boldref_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz
source_mask = <undefined>
source_oob = <undefined>
subject_id = sub-1390
subjects_dir = /out/sourcedata/freesurfer

Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node mri_coreg.

Cmdline:
	mri_coreg --s sub-1390 --dof 6 --ftol 1.000000e-04 --linmintol 1.000000e-02 --threads 1 --lta /scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta --sep 4 --mov /scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/bold_reg_wf/bbreg_wf/mri_coreg/clipped.nii.gz --sd /out/sourcedata/freesurfer
Stdout:

Stderr:
	Segmentation fault
Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._post_run_hook(runtime)
	  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/niworkflows/interfaces/freesurfer.py", line 248, in _post_run_hook
	    fix_lta_length(lta_file)
	  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/niworkflows/interfaces/freesurfer.py", line 399, in fix_lta_length
	    lines = Path(lta_file).read_text().splitlines(keepends=True)
	  File "/opt/conda/envs/nibabies/lib/python3.10/pathlib.py", line 1134, in read_text
	    with self.open(mode='r', encoding=encoding, errors=errors) as f:
	  File "/opt/conda/envs/nibabies/lib/python3.10/pathlib.py", line 1119, in open
	    return self._accessor.open(self, mode, buffering, encoding, errors,
	FileNotFoundError: [Errno 2] No such file or directory: '/scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta'
```

### Add any additional information or context about the problem here.

According to the crash log, The `mri_coreg` command is called, and a path to a `registration.lta` file is hardcoded into the command:

```
Cmdline:
	mri_coreg --s sub-1390 --dof 6 --ftol 1.000000e-04 --linmintol 1.000000e-02 --threads 1 --lta /scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta --sep 4 --mov /scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/bold_reg_wf/bbreg_wf/mri_coreg/clipped.nii.gz --sd /out/sourcedata/freesurfer
Stdout:
```

The problem is that no `registration.lta` files are being generated for my subjects.  I'm unsure of whether this file should be generated  (and if so, what workflow is responsible for generating it), or if Nibabies should gracefully handle the scenario where it is missing?

**Comment by effigies** [comment]
The problem is:

```
Stderr:
	Segmentation fault
```

The LTA file doesn't exist because `mri_coreg` doesn't create it before crashing. The exception that it can't find the file is an unfortunate behavior of recent versions of nipype, which causes this confusion regularly.

I would look at the input file `/scratch/nibabies_24_1_wf/single_subject_1390_newborn_wf/func_preproc_ses_newborn_task_restPA_run_01_wf/final_boldref_wf/clip_bg_noise/mapflow/_clip_bg_noise0/clipped.nii.gz` and see if that looks reasonable.

**Comment by scott-huberty** [comment]
Ahh ok I see.. thank you @effigies ! 🙏

**Comment by scott-huberty** [comment]
Just wanted to update here.. So long story short, I think I've been able to isolate this issue to MCRIBS. If we use MCRIBS for the anatomical workflow, we'll hit the aforementioned error. If We use InfantFS, The full pipeline (Anatomical + Functional) will run without trouble. So AFAICT, there seems to be something with the output of MCRIBS that is causing this issue down the line. Though I don't know exactly what is going on yet.. Granted @mgxd has [mentioned before](https://github.com/nipreps/nibabies/discussions/359#discussioncomment-9237362) that MCRIBS can be very brittle.



> and see if that looks reasonable.

This is the `clipped.nii.gz` file from the failed run. Nothing egregious stands out to me? Though I'll need to take a look at this same file after the successful run (where infantfs was used).

<img width="2560" alt="Screen Shot 2024-05-28 at 6 25 12 PM" src="https://github.com/nipreps/nibabies/assets/52462026/9a7e124b-e514-4e05-a03b-8d7e26b92950">
