### ISSUE TITLE
`unstable` docker tag is lagging behind Nibabies development version

### ISSUE THREAD

**Issue by scott-huberty** [nipreps/nibabies#372]
The [documentation](https://nibabies.readthedocs.io/en/latest/installation.html#working-with-docker) says:

> To pull an image, the specific version tag must be specified in order to pull the images ... `unstable` points to the most recent developmental change

But running  ```docker pull nipreps/nibabies:unstable```

Pulls an image that was last updated _2 months ago._ As a result, using the development version of Nibabies with the unstable Docker tag will immediately fail with an import error.

<details><summary>Sample command</summary>

```
docker run -it \
  -v /path/to/bids:/data:ro \
  -v /path/to/derivatives/Nibabies:/out \
  -v /path/to/derivatives/work/nibabies_work:/scratch \
  -v /path/to/freesurfer_license/license.txt:/opt/freesurfer/license.txt:ro \
  -v /path/to/devel/repos/nibabies/nibabies:/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies:ro \
  nipreps/nibabies:unstable \
  /data /out participant \
  --age-months 6 \
  --participant-label 999 \
  -w /scratch \
  --surface-recon-method freesurfer \
``` 

</details>

<details><summary>Stack Trace</summary>

```console

Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/bin/nibabies", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/run.py", line 62, in main
    retval = build_workflow(config_file)
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/workflow.py", line 19, in build_workflow
    from ..reports.core import generate_reports
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/reports/core.py", line 5, in <module>
    from nibabies.data import load as load_data
  File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/data/__init__.py", line 1, in <module>
    from acres import Loader
```

</details>

A workaround is to specify the version number (24.0.0rc0) in the docker run command, raising the question: Does the documentation need to be corrected, or does the `unstable` nibabies docker image need to be updated?

**Comment by mgxd** [comment]
This is fixed after #379

**Comment by scott-huberty** [comment]
Thanks @mgxd 🙏
