### ISSUE TITLE
Errors may be present in "successful" runs

### ISSUE THREAD

**Issue by mgxd** [nipreps/nibabies#392]
### What happened?

Popped up in the CI.

https://circleci.com/api/v1.1/project/github/nipreps/nibabies/2851/output/112/0?file=true&allocation-id=66d385c23adb526541491dea-0-build%2FABCDEFGH

Specifically, a crash occurs:

```
240831-21:10:41,685 nipype.workflow WARNING:
	 [Node] Error on "nibabies_24_1_wf.fsdir_run_20240831_211035_585ba987_6362_4fdc_adf4_96fbcefd71f4" (/scratch/nibabies_24_1_wf/fsdir_run_20240831_211035_585ba987_6362_4fdc_adf4_96fbcefd71f4)
240831-21:10:41,686 nipype.workflow ERROR:
	 Node fsdir_run_20240831_211035_585ba987_6362_4fdc_adf4_96fbcefd71f4 failed to run on host b68c6b836a11.
240831-21:10:41,686 nipype.workflow ERROR:
	 Saving crash info to /out/logs/crash-20240831-211041-UID1001-fsdir_run_20240831_211035_585ba987_6362_4fdc_adf4_96fbcefd71f4-e569a10e-8616-4885-b226-b83db48dbfed.txt
Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fsdir_run_20240831_211035_585ba987_6362_4fdc_adf4_96fbcefd71f4.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/niworkflows/interfaces/bids.py", line 1475, in _run_interface
	    shutil.copytree(source, dest, copy_function=shutil.copy)
	  File "/opt/conda/envs/nibabies/lib/python3.11/shutil.py", line 573, in copytree
	    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/nibabies/lib/python3.11/shutil.py", line 471, in _copytree
	    os.makedirs(dst, exist_ok=dirs_exist_ok)
	  File "<frozen os>", line 225, in makedirs
	PermissionError: [Errno 13] Permission denied: '/opt/subjects/fsaverage'
```

yet the log ends with

```
240831-21:19:39,613 nipype.workflow IMPORTANT:
	 nibabies finished successfully!
240831-21:19:39,613 nipype.workflow IMPORTANT:
	 Works derived from this nibabies execution should include the boilerplate text found in <OUTPUT_PATH>/logs/CITATION.md.
```

### What command did you use?

```shell
docker run --rm -e DOCKER_VERSION_8395080871=26.0.2 -it -u 1001:1002 --network=none -e NIBABIES_DEV=1 -v /tmp/fslicense/license.txt:/opt/freesurfer/license.txt:ro -v /tmp/data/bcp:/data:ro -v /tmp/bcp/derivatives/nibabies:/out -v /tmp/data/bcp/derivatives/infant-freesurfer:/opt/subjects -v /tmp/data/bcp/derivatives/bibsnet:/deriv/precomputed:ro -v /tmp/bcp/work:/scratch -v opts.config:/home/fmriprep/.nipype/nipype.cfg:ro nipreps/nibabies:dev /data /out participant --notrack --skull-strip-template UNCInfant:cohort-1 --sloppy --write-graph --mem-mb 14000 --nthreads 4 -vv --age-months 2 --sloppy --surface-recon-method infantfs --output-layout bids --anat-only --fs-subjects-dir /opt/subjects --derivatives precomputed=/deriv/precomputed -w /scratch --output-spaces MNIInfant:cohort-1 func
```

### What version of NiBabies are you using?

24.0.1

**Comment by dnkennedy** [comment]
+1 to this, I just got it in a trial of 24.1.0
