### ISSUE TITLE
SyN SDC incomplete

### ISSUE THREAD

**Issue by mgxd** [nipreps/nibabies#393]
### What happened?

When running the SyN portion of the pipeline:

```
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fmap_select_std.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 429, in aggregate_outputs
	    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
	                        ^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/niworkflows/interfaces/utility.py", line 217, in _list_outputs
	    index = self.inputs.keys.index(self.inputs.key)
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	ValueError: 'MNI152NLin2009cAsym' is not in list
```

The offending section:
https://github.com/nipreps/nibabies/blob/8e2415f247943167811eb0a7cdedc3867b96e7cb/nibabies/workflows/base.py#L597-L607

SDCFlows is hardcoded to using an atlas -> MNI152NLin2009cAsym transform
https://github.com/nipreps/sdcflows/blob/08e198f1f62422d2d6274ed93a3b4ba7a78d661a/sdcflows/workflows/fit/syn.py#L441-L459

The easiest solution is probably supplement this with an MNIInfant -> MNI152 transform (originally discussed in https://github.com/nipreps/nibabies/issues/153), but curious to hear other input (cc @oesteban @effigies)

### What command did you use?

```shell
nibabies /data /out participant --participant-label 216075 --omp-nthreads 4 --mem 14000 --nprocs 4 --notrack -vv --project-goodvoxels --copy-derivatives --stop-on-first-crash --use-syn-sdc --force-syn --ignore fieldmaps --level full --surface-recon-method mcribs --cifti-output -s V02 --fs-subjects-dir /opt/subjects --derivatives anat=/deriv/anat -w /scratch
```

### What version of NiBabies are you using?

24.0.1

**Comment by mgxd** [comment]
The problem lies within [sdcflow's `init_syn_preprocessing_wf` using an adult B0 image as a prior, and warping it to `MNI152NLin2009cAsym`](https://github.com/nipreps/sdcflows/blob/82f419bc398e96135729aad5a84ada798de81635/sdcflows/workflows/fit/syn.py#L438-L447). For infants, a few ideas, from easier to harder

- Drop using the prior for SyN regularization
- Use an infant B0 as prior, and modify workflow to use `MNIInfant` space
