### ISSUE TITLE
Only T2w image

### ISSUE THREAD

**Issue by seonjoo** [nipreps/nibabies#411]
### What happened?

I have only T2w and BOLD images. But it keeps givine me errors: "FileNotFoundError: No T1w images found for subject". The current implementation of NiBabies do not handle the cases without T1 image? Or is it a bug?

### What command did you use?

```shell
docker run --rm -e -it -v ${datadir}:/data:ro -v ${outputdir}:/out -v license.txt:/opt/freesurfer/license.txt:ro nipreps/nibabies:24.1.0 /data /out participant --participant-label ${subID} --output-spaces T2w fsaverage --anat-only --reference-anat T2w --bold2anat-init t2w --ignore fieldmaps t1w
```

### What version of NiBabies are you using?

24.1.0

### Relevant log output

```shell
File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nibabies/cli/run.py", line 104, in main
    nibabies_wf.run(**_plugin)
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/plugins/base.py", line 224, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node bidssrc.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/nibabies/lib/python3.11/site-packages/niworkflows/interfaces/bids.py", line 282, in _run_interface
	    raise FileNotFoundError(
	FileNotFoundError: No T1w images found for subject sub-XXX
```

**Comment by mgxd** [comment]
Good catch, I see the problem - it is a bug, the bidssrc node conditionally allows no T1w https://github.com/nipreps/niworkflows/blob/7bd6a53e313843dbaccd2d9d21c438ccd1642489/niworkflows/interfaces/bids.py#L273

We haven't hit this as we've only tried running T2w-only with precomputed derivatives (mask, segmentation) since MCRIBS is quite fickle
